# Select an image from https://hub.docker.com/_/php/.
image: php:7.4

stages:
  - build
  - prepare
  - test

services:
  - docker:dind

before_script:
  - docker info


cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - vendor/

build:image:
  stage: build
  image: docker:latest
  only:
    changes:
      - Dockerfiles/**
      - .gitlab-ci.yml
      
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:testrunner -f Dockerfiles/testrunner/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:testrunner

test:composerinstall:
  stage: build
  only:
    changes:
      - composer.json
  script: 
   composer install
  artifacts:
    paths:
      - vendor
      


test:behat:
  stage: test
  image: $CI_REGISTRY_IMAGE:testrunner
  before_script:
    - composer install
  script:
    - vendor/bin/behat --tags '~@pending'
    - ls
  allow_failure: true
  dependencies:
    - test:composerinstall
