# Select an image from https://hub.docker.com/_/php/.
image: php:7.4

stages:
  - build
  - test

services:
  - docker:dind

before_script:
  - docker info

cache:
  paths:
  - vendor/

build:image:
  stage: build
  image: docker:latest
  only:
    changes:
      - Dockerfiles/**
      - .gitlab-ci.yml
      
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:testrunner -f Dockerfiles/testrunner/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:testrunner

test:behat:
  stage: build
  image: $CI_REGISTRY_IMAGE:testrunner
  before_script:
    - composer install
  script:
    - vendor/bin/behat --tags '~@pending'
    - ls
  allow_failure: true
