# Select an image from https://hub.docker.com/_/php/.
image: php:7.3

stages:
  - test
   
# Select what we should cache
cache:
  paths:
  - vendor/

before_script:
# Install git, the php image doesn't have installed
- apt-get update -yqq
- apt-get install git -yqq

# Install mysql driver
- docker-php-ext-install pdo_mysql
# Install composer
- curl -sS https://getcomposer.org/installer | php
# Install all project dependencies
- php composer.phar install

test:behat:    
  script:
  - vendor/bin/behat --tags '~@pending'
  allow_failure: true
