# Select an image from https://hub.docker.com/_/php/.
image: php:7.4

stages:
  - build_image
  - test

before_script:
  - docker info
# Select what we should cache
cache:
  paths:
  - vendor/


build_image:
  image: php:7.4
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:testrunner -f dockerfiles/testrunner/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:testrunner
    
    
test:behat:
 image: $CI_REGISTRY_IMAGE:testrunner
  before_script:
    - composer install
  script:
    - vendor/bin/behat --tags '~@pending'
  allow_failure: true
